language: go

go:
  - 1.9.x
  - master
before_install:
  - git clone git://github.com/golang/sys.git
  - mkdir -p $GOPATH/src/golang.org/x/
  - mv sys $GOPATH/src/golang.org/x/
install:
  - go get github.com/go-sql-driver/mysql
  - go get github.com/astaxie/beego
  - go get github.com/blevesearch/bleve
  - go get github.com/yanyiwu/gojieba
  - go get github.com/shirou/gopsutil
  - go get github.com/tealeg/xlsx
  - go get github.com/PuerkitoBio/goquery
  - go get github.com/garyburd/redigo/redis
  - go get github.com/huichen/wukong
script:
  - go test -v ./...
