language: go

go:
  - 1.9.x
  - master
install:
  - go get github.com/go-sql-driver/mysql
  - go get github.com/astaxie/beego
  - go get github.com/blevesearch/bleve
  - go get github.com/yanyiwu/gojieba
  - go get github.com/shirou/gopsutil
  - go get github.com/tealeg/xlsx
  - go get github.com/PuerkitoBio/goquery
  - go get github.com/garyburd/redigo/redis
  - go get github.com/huichen/wukong
  - go get -u github.com/golang/sys
script:
  - go test -v ./...
